const colors = {
  light: {
    text: "#0D0D0D",
    tint: "#FF4500",
    background: "#F0F0F0",
    foreground: "#0D0D0D",
    card: "#FFFFFF",
    cardForeground: "#0D0D0D",
    primary: "#FF4500",
    primaryForeground: "#FFFFFF",
    secondary: "#E8E8E8",
    secondaryForeground: "#1A1A1A",
    muted: "#E8E8E8",
    mutedForeground: "#737373",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0E0",
    input: "#E0E0E0",
    success: "#22C55E",
    successForeground: "#FFFFFF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF4500",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#FF4500",
    primaryForeground: "#FFFFFF",
    secondary: "#252525",
    secondaryForeground: "#FFFFFF",
    muted: "#252525",
    mutedForeground: "#888888",
    accent: "#FF6B35",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
    success: "#22C55E",
    successForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
